### ISSUE TITLE
NameError("name 'call' is not defined",)

### ISSUE THREAD

**Issue by XUEZIJIAN** [yuce/pyswip#38]
Hello
I got this error when I ran the 'Pythonic interface (Experimental)' example.
Is it because I am missing something?
Thanks 

py3.6
swipl1.6.4

Traceback (most recent call last):
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 111, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\debugger.py", line 36, in debug
    run(address, filename, *args, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 47, in run_file
    run(argv, addr, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\_main.py", line 98, in _run
    _pydevd.main()
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1628, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\pydevd.py", line 1035, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Python\Core\Packages\ptvsd\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Project\AI_NLP\AI_NLP\test.py", line 9, in <module>
    call(assertz(father("michael","john")))
NameError: name 'call' is not defined

**Comment by GraceGay** [comment]
maybe you can try to add one line like 'from pyswip import call'.  and you may still encounter another error, then you should modify the one line of code to 'assertz = Functor("assertz", 1)'

**Comment by yuce** [comment]
@XUEZIJIAN @GraceGay 's fix is correct, I've updated the README.
