### ISSUE TITLE
Windows 10 import error

### ISSUE THREAD

**Issue by mrzephros** [yuce/pyswip#70]
Hi, I keep having this issue everytime i import pyswip

```
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from pyswip import Prolog
  File "c:\python\python37-32\lib\site-packages\pyswip\__init__.py", line 29, in <module>
    from pyswip.prolog import Prolog
  File "c:\python\python37-32\lib\site-packages\pyswip\prolog.py", line 28, in <module>
    from pyswip.core import *
  File "c:\python\python37-32\lib\site-packages\pyswip\core.py", line 573, in <module>
    _lib = CDLL(_path, mode=RTLD_GLOBAL)
  File "c:\python\python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```
Please help!

**Comment by mrzephros** [comment]
It's ok i solved it!

**Comment by nodyyu89** [comment]
how do you solve it :D

**Comment by mrzephros** [comment]
Just make sure your prolog and python are both 64bit or both are 32bit
