### ISSUE TITLE
Error on string unification in foreign function

### ISSUE THREAD

**Issue by keraJLi** [yuce/pyswip#89]
If I try to run the following minimal example
```python
from pyswip import Prolog, registerForeign

def foo(a):
    a.unify("bar")
    return True

registerForeign(foo, arity=1)
prolog = Prolog()
print(list(prolog.query("foo(A)")))
```
I get the following error:
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File ".../pyswip_env/lib/python3.7/site-packages/pyswip/easy.py", line 475, in wrapper
    r = fun(*args)
  File ".../test.py", line 6, in foo
    a.unify("bar")
  File ".../pyswip_env/lib/python3.7/site-packages/pyswip/easy.py", line 155, in unify
    fun = PL_unify_atom_chars
NameError: name 'PL_unify_atom_chars' is not defined
Traceback (most recent call last):
  File ".../test2.py", line 14, in <module>
    print(list(prolog.query("foo(A)")))
  File ".../pyswip_env/lib/python3.7/site-packages/pyswip/prolog.py", line 127, in __call__
    "Returned: '", str(term), "'."]))
pyswip.prolog.PrologError: Caused by: 'foo(A)'. Returned: 'error(domain_error(foreign_return_value, 94083715460032), context(/(foo, 1), _1836))'.
```
How can I unify a variable with a string?

**Comment by keraJLi** [comment]
Fixed in b0434e4008c5ce9a74e19314f611e3dde2b7eb85. Thanks!
